# Generated by Django 3.0.2 on 2021-03-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.CharField(choices=[('Группа поддержки пользователей', 'Группа поддержки пользователей'), ('Группа сетевых технологий', 'Группа сетевых технологий'), ('Группа разработки', 'Группа разработки')], default='group1', max_length=100),
        ),
    ]
