# Generated by Django 3.0.2 on 2021-03-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_accounting', '0002_auto_20210320_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('В работе', 'В работе'), ('Отменена', 'Отменена')], default=('Выполнена', 'Выполнена'), max_length=100),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.CharField(choices=[('Группа поддержки пользователей', 'Группа поддержки пользователей'), ('Группа сетевых технологий', 'Группа сетевых технологий'), ('Группа разработки', 'Группа разработки')], default=('Группа поддержки пользователей', 'Группа поддержки пользователей'), max_length=100),
        ),
    ]
