# Generated by Django 3.0.2 on 2021-03-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_accounting', '0003_auto_20210320_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('В работе', 'В работе'), ('Отменена', 'Отменена')], default=('В работе', 'В работе'), max_length=100),
        ),
    ]
