# Generated by Django 3.0.2 on 2021-03-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_accounting', '0004_auto_20210320_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='check',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
    ]
