# Generated by Django 3.0.2 on 2021-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_accounting', '0005_auto_20210320_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.CharField(choices=[[1, 'lecterers'], [2, 'super'], [3, 'Группа поддержки пользователей'], [4, 'Группа сетевых технологий'], [5, 'Группа разработки']], default=[1, 'lecterers'], max_length=100),
        ),
    ]
